### PR TITLE
Configuration tools for AWS

### PR DESCRIPTION
**Pull request by ryscher**
These files and scripts make it easier to configure new machines on AWS.

### CODE REVIEW

**Comment by ryscher** [comment]
This doesn't need to be merged yet.... I will be adding more pieces.

**Comment by ryscher** [comment]
Since I apparently haven't found the need to add anything in a long time, this is ready to review.

**Comment by daisieh** [comment]
It looks like the aliases are all Ryan-specific aliases?

**Comment by daisieh** [comment]
To be clear: I don't think that we should be merging Ryan-specific aliases as a matter of course to the datadryad master branch. For example, I have never used something like this `alias cd.....='cd ../../../..'` command; it's not particularly necessary for Dryad. I definitely don't think `alias dev='ssh rsdryad@dryaddev2.lib.ncsu.edu'` is something that we need all of us to have access to.

Please remove anything that is Ryan-specific and then perhaps we can discuss merging the rest into the master branch.

**Comment by ryscher** [comment]
Oh, I forgot about this PR.... I've moved all of my specific stuff into https://github.com/ryscher/ryans-env

There's nothing in here worth keeping. Closing.

**Pull request closed without merging**
