### PR TITLE
Ensure format is set to 'unknown' when the file format doesn't match …

### PR DESCRIPTION
**Pull request by ryscher**
…anything in the registry

### CODE REVIEW

**Comment by daisieh** [comment]
Has this been tested?

**Comment by dfagandryad** [comment]
The large file replacement script failed for .nc files from a submission (doi:10.5061/dryad.1597g). The error message displayed included the following: 'ERROR:  syntax error at or near "rows" LINE 1: ...ece758ddd4fd7fc4b7665433', bitstream_format_id=(0 rows) wher...'. After investigation, it was determined that the failure likely occurred because we don’t have an entry in the format registry for .nc files. Once the .nc file type was added to the format registry, we attempted the large file transfer script again, and the script completed without any problems and the file replacement was successful.

**Comment by daisieh** [comment]
@dfagandryad, I don't understand...was the error you're talking about before or after Ryan's fix?

**Comment by dfagandryad** [comment]
The error was before Ryan's fix. He asked me to make a note in the pull request. I will edit the note to make that clear.

**Comment by daisieh** [comment]
Okay, this looks fine. Merging.

**Pull request merged**
