### PR TITLE
EZID updates

### PR DESCRIPTION
**Pull request by daisieh**
Refactored DOI code to use the Python module specified in https://support.datacite.org/docs/datacite-ez-api-guide instead of doing things piecemeal with a copy of the code.

Now if you want to test Datacite instead of EZID, you can export an environment variable called `DOI_SERVER` and specify the Datacite server instead of the default EZID one.

### CODE REVIEW

**Comment by daisieh** [comment]
This isn't actually ready for testing with DataCite yet: apparently they didn't actually implement all of the functionality, and one-time username/password login is not a thing they implemented.

**Comment by daisieh** [comment]
I've opened an issue at https://github.com/datacite/datacite/issues/354 to see if I can get some clarification.

**Comment by daisieh** [comment]
Okay. I had to update the EZID.py file locally in order to disable the one-time authentication method. It should work now.

**Comment by daisieh** [comment]
(I've also emailed the creator of the EZID package to see if he'll update it to work with DataCite.)

**Comment by ryscher** [comment]
Verified that this tool is working with both EZID and DataCite.

**Pull request merged**
